<h1>
Is brutality committed in the name of patriotism more justified than violence committed in the name of parallel ideologies, be it Maoism, communalism, or Hindu nationalism? Who determines the hierarchy of causes and the amount of "collateral damage" allowed each? In his article 'A spring long past' Dilip Simeon reveals the hypocrisy of ideology when lives are at stake, and the transparency of symbols when death lurks around the corner. s brutality committed in the name of patriotism more justified than violence committed in the name of parallel ideologies, be it Maoism, communalism, or Hindu nationalism? Who determines the of "collateral damage" allowed each? In his article 'A spring long past'
</h1>
<h1>
Is brutality committed in the name of patriotism more justified than violence committed in the name of parallel ideologies, be it Maoism, communalism, or Hindu nationalism? Who determines the hierarchy of causes and the amount of "collateral damage" allowed each? In his article 'A spring long past' Dilip Simeon reveals the hypocrisy of ideology when lives are at stake, and the transparency of symbols when death lurks around the corner. s brutality committed in the name of patriotism more justified than violence committed in the name of parallel ideologies, be it Maoism, communalism, or Hindu nationalism? Who determines the of "collateral damage" allowed each? In his article 'A spring long past'
</h1>
<h1>
Is brutality committed in the name of patriotism more justified than violence committed in the name of parallel ideologies, be it Maoism, communalism, or Hindu nationalism? Who determines the hierarchy of causes and the amount of "collateral damage" allowed each? In his article 'A spring long past' Dilip Simeon reveals the hypocrisy of ideology when lives are at stake, and the transparency of symbols when death lurks around the corner. s brutality committed in the name of patriotism more justified than violence committed in the name of parallel ideologies, be it Maoism, communalism, or Hindu nationalism? Who determines the of "collateral damage" allowed each? In his article 'A spring long past'
</h1>
<h1>
Is brutality committed in the name of patriotism more justified than violence committed in the name of parallel ideologies, be it Maoism, communalism, or Hindu nationalism? Who determines the hierarchy of causes and the amount of "collateral damage" allowed each? In his article 'A spring long past' Dilip Simeon reveals the hypocrisy of ideology when lives are at stake, and the transparency of symbols when death lurks around the corner. s brutality committed in the name of patriotism more justified than violence committed in the name of parallel ideologies, be it Maoism, communalism, or Hindu nationalism? Who determines the of "collateral damage" allowed each? In his article 'A spring long past'
</h1>
<h1>
Is brutality committed in the name of patriotism more justified than violence committed in the name of parallel ideologies, be it Maoism, communalism, or Hindu nationalism? Who determines the hierarchy of causes and the amount of "collateral damage" allowed each? In his article 'A spring long past' Dilip Simeon reveals the hypocrisy of ideology when lives are at stake, and the transparency of symbols when death lurks around the corner. s brutality committed in the name of patriotism more justified than violence committed in the name of parallel ideologies, be it Maoism, communalism, or Hindu nationalism? Who determines the of "collateral damage" allowed each? In his article 'A spring long past'
</h1>